name: publish
on:
  push:
    tags:
      - 'v*' # Trigger the workflow when a tag starting with "v" is pushed
      
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          tag=${GITHUB_REF#refs/tags/}
          tag=${tag:1}
          image=ghcr.io/${GITHUB_REPOSITORY}
          echo "IMAGE: ${image}"
          echo "TAG: ${tag}"
          docker build . --tag ${image}:latest
          docker push ${image}:latest
          docker build . --tag ${image}:${tag}
          docker push ${image}:${tag}
          