name: publish-dockerhub
on:
  push:
    tags:
      - 'v*' # Trigger the workflow when a tag starting with "v" is pushed
      
jobs:
  publish-dockerhub-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        run: |
          tag=${GITHUB_REF#refs/tags/}
          tag=${tag:1}
          image=docker.io/mitchallen/random-server
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${image}:${tag} \
            -t ${image}:latest \
            --push .

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mitchallen/random-server
          readme-filepath: ./README.md
