name: publish
on:
  push:
    tags:
      - 'v*' # Trigger the workflow when a tag starting with "v" is pushed
      
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          tag=${GITHUB_REF#refs/tags/}
          tag=${tag:1}
          echo "TAG: ${tag}"
          # docker build . --tag ghcr.io/mitchallen/random-server:latest
          # docker push ghcr.io/mitchallen/random-server:latest
          docker build . --tag ghcr.io/mitchallen/random-server:${tag}
          docker push ghcr.io/mitchallen/random-server:${tag}
          